# Generated by Django 3.1.4 on 2021-10-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=30)),
                ('git_command', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Version Setting',
                'verbose_name_plural': 'Version Settings',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='file_uploads')),
                ('speech_to_text', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('output', models.TextField()),
                ('time', models.DecimalField(decimal_places=6, max_digits=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voice',
                'verbose_name_plural': 'Voices',
                'ordering': ('-id',),
            },
        ),
    ]
