# Generated by Django 3.1.4 on 2021-10-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_voice_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatVersionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='enter version of the Flat weights', max_length=30)),
                ('git_command', models.CharField(help_text='enter the git link here', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Version Flat Setting',
                'verbose_name_plural': 'Version Settings',
            },
        ),
    ]
