# Generated by Django 3.1.4 on 2021-10-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flatversionsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatversionsettings',
            options={'verbose_name': 'Version Flat Setting', 'verbose_name_plural': 'Version Flat Settings'},
        ),
    ]
