# Generated by Django 3.1.4 on 2021-11-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211022_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='bot_id',
            field=models.CharField(max_length=500),
        ),
    ]
